# Generated by Django 5.1.11 on 2025-08-30 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_group_polluser_telegram_id_pollusergroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='polluser',
            name='is_professor',
        ),
        migrations.RemoveField(
            model_name='polluser',
            name='register',
        ),
        migrations.AddField(
            model_name='polluser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polluser',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='polluser',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
