# Generated by Django 5.1.7 on 2025-03-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_question_status_quiz_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(default=None),
        ),
    ]
