# Generated by Django 5.1.7 on 2025-03-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_quiz_end_time_quiz_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
